sudo: required
services:
  - docker 
  
before_install:
  - docker build -t balajitech87/docker-react -f dockerfile.dev .
  
  
script:
  - docker run balajitech87/docker-react npm run test -- --coverage