version: '3'
services:
  webapp:
    build: 
      context: .
      dockerfile: dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
  webapp-tests:
    build:
      context:
        dockerfile: dockerfile.dev
     volumes:
      - /usr/app/node_modules
     command: ["npm", "run", "test"]